raceMapping = {
    "2018": [
        ("1", "Australian Grand Prix"),
        ("2", "Bahrain Grand Prix"),
        ("3", "Chinese Grand Prix"),
        ("4", "Azerbaijan Grand Prix"),
        ("5", "Spanish Grand Prix"),
        ("6", "Monaco Grand Prix"),
        ("7", "Canadian Grand Prix"),
        ("8", "French Grand Prix"),
        ("9", "Austrian Grand Prix"),
        ("10", "British Grand Prix"),
        ("11", "German Grand Prix"),
        ("12", "Hungarian Grand Prix"),
        ("13", "Belgian Grand Prix"),
        ("14", "Italian Grand Prix"),
        ("15", "Singapore Grand Prix"),
        ("16", "Russian Grand Prix"),
        ("17", "Japanese Grand Prix"),
        ("18", "United States Grand Prix"),
        ("19", "Mexican Grand Prix"),
        ("20", "São Paulo Grand Prix"),
        ("21", "Abu Dhabi Grand Prix")
    ],

    "2019": [
        ("1", "Australian Grand Prix"),
        ("2", "Bahrain Grand Prix"),
        ("3", "Chinese Grand Prix"),
        ("4", "Azerbaijan Grand Prix"),
        ("5", "Spanish Grand Prix"),
        ("6", "Monaco Grand Prix"),
        ("7", "Canadian Grand Prix"),
        ("8", "French Grand Prix"),
        ("9", "Austrian Grand Prix"),
        ("10", "British Grand Prix"),
        ("11", "German Grand Prix"),
        ("12", "Hungarian Grand Prix"),
        ("13", "Belgian Grand Prix"),
        ("14", "Italian Grand Prix"),
        ("15", "Singapore Grand Prix"),
        ("16", "Russian Grand Prix"),
        ("17", "Japanese Grand Prix"),
        ("18", "Mexican Grand Prix"),
        ("19", "United States Grand Prix"),
        ("20", "São Paulo Grand Prix"),
        ("21", "Abu Dhabi Grand Prix")
    ],

    "2020": [
        ("1", "Austrian Grand Prix"),
        ("2", "Styrian Grand Prix"),
        ("3", "Hungarian Grand Prix"),
        ("4", "British Grand Prix"),
        ("5", "70th Anniversary Grand Prix"),
        ("6", "Spanish Grand Prix"),
        ("7", "Belgian Grand Prix"),
        ("8", "Italian Grand Prix"),
        ("9", "Tuscan Grand Prix"),
        ("10", "Russian Grand Prix"),
        ("11", "Eifel Grand Prix"),
        ("12", "Portuguese Grand Prix"),
        ("13", "Emilia-Romagna Grand Prix"),
        ("14", "Turkish Grand Prix"),
        ("15", "Bahrain Grand Prix"),
        ("16", "Sakhir Grand Prix"),
        ("17", "Abu Dhabi Grand Prix")
    ],

    "2021": [
        ("1", "Bahrain Grand Prix"),
        ("2", "Emilia-Romagna Grand Prix"),
        ("3", "Portuguese Grand Prix"),
        ("4", "Spanish Grand Prix"),
        ("5", "Monaco Grand Prix"),
        ("6", "Azerbaijan Grand Prix"),
        ("7", "French Grand Prix"),
        ("8", "Styrian Grand Prix"),
        ("9", "Austrian Grand Prix"),
        ("10S", "British Sprint Race"),
        ("10", "British Grand Prix"),
        ("11", "Hungarian Grand Prix"),
        ("12", "Belgian Grand Prix"),
        ("13", "Dutch Grand Prix"),
        ("14S", "Italian Sprint Race"),
        ("14", "Italian Grand Prix"),
        ("15", "Russian Grand Prix"),
        ("16", "Turkish Grand Prix"),
        ("17", "United States Grand Prix"),
        ("18", "Mexico City Grand Prix"),
        ("19S", "São Paulo Sprint Race"),
        ("19", "São Paulo Grand Prix"),
        ("20", "Qatar Grand Prix"),
        ("21", "Saudi Arabian Grand Prix"),
        ("22", "Abu Dhabi Grand Prix")
    ],

    "2022": [
        ("1", "Bahrain Grand Prix"),
        ("2", "Saudi Arabian Grand Prix"),
        ("3", "Australian Grand Prix"),
        ("4S", "Emilia-Romagna Sprint Race"),
        ("4", "Emilia-Romagna Grand Prix"),
        ("5", "Miami Grand Prix"),
        ("6", "Spanish Grand Prix"),
        ("7", "Monaco Grand Prix"),
        ("8", "Azerbaijan Grand Prix"),
        ("9", "Canadian Grand Prix"),
        ("10", "British Grand Prix"),
        ("11S", "Austrian Sprint Race"),
        ("11", "Austrian Grand Prix"),
        ("12", "French Grand Prix"),
        ("13", "Hungarian Grand Prix"),
        ("14", "Belgian Grand Prix"),
        ("15", "Dutch Grand Prix"),
        ("16", "Italian Grand Prix"),
        ("17", "Singapore Grand Prix"),
        ("18", "Japanese Grand Prix"),
        ("19", "United States Grand Prix"),
        ("20", "Mexico City Grand Prix"),
        ("21S", "São Paulo Sprint Race"),
        ("21", "São Paulo Grand Prix"),
        ("22", "Abu Dhabi Grand Prix")
    ],

    "2023": [
        ("1", "Bahrain Grand Prix"),
        ("2", "Saudi Arabian Grand Prix"),
        ("3", "Australian Grand Prix"),
        ("4S", "Azerbaijan Sprint Race"),
        ("4", "Azerbaijan Grand Prix"),
        ("5", "Miami Grand Prix"),
        ("6", "Monaco Grand Prix"),
        ("7", "Spanish Grand Prix"),
        ("8", "Canadian Grand Prix"),
        ("9S", "Austrian Sprint Race"),
        ("9", "Austrian Grand Prix"),
        ("10", "British Grand Prix"),
        ("11", "Hungarian Grand Prix"),
        ("12S", "Belgian Sprint Race"),
        ("12", "Belgian Grand Prix"),
        ("13", "Dutch Grand Prix"),
        ("14", "Italian Grand Prix"),
        ("15", "Singapore Grand Prix"),
        ("16", "Japanese Grand Prix"),
        ("17S", "Qatar Sprint Race"),
        ("17", "Qatar Grand Prix"),
        ("18S", "United States Sprint Race"),
        ("18", "United States Grand Prix"),
        ("19", "Mexico City Grand Prix"),
        ("20S", "São Paulo Sprint Race"),
        ("20", "São Paulo Grand Prix"),
        ("21", "Las Vegas Grand Prix"),
        ("22", "Abu Dhabi Grand Prix")
    ],

    "2024": [
        ("1", "Bahrain Grand Prix"),
        ("2", "Saudi Arabian Grand Prix"),
        ("3", "Australian Grand Prix"),
        ("4", "Japanese Grand Prix"),
        ("5S", "Chinese Sprint Race"),
        ("5", "Chinese Grand Prix"),
        ("6S", "Miami Sprint Race"),
        ("6", "Miami Grand Prix"),
        ("7", "Emilia-Romagna Grand Prix"),
        ("8", "Monaco Grand Prix"),
        ("9", "Canadian Grand Prix"),
        ("10", "Spanish Grand Prix"),
        ("11S", "Austrian Sprint Race"),
        ("11", "Austrian Grand Prix"),
        ("12", "British Grand Prix"),
        ("13", "Hungarian Grand Prix"),
        ("14", "Belgian Grand Prix"),
        ("15", "Dutch Grand Prix"),
        ("16", "Italian Grand Prix"),
        ("17", "Azerbaijan Grand Prix"),
        ("18", "Singapore Grand Prix"),
        ("19S", "United States Sprint Race"),
        ("19", "United States Grand Prix"),
        ("20", "Mexico city Grand Prix"),
        ("21S", "São Paulo Sprint Race"),
        ("21", "São Paulo Grand Prix"),
        ("22", "Las Vegas Grand Prix"),
        ("23S", "Qatar Sprint Race"),
        ("23", "Qatar Grand Prix"),
        ("24", "Abu Dhabi Grand Prix")
    ],

    "2025": [
        ("1", "Australian Grand Prix"),
        ("2S", "Chinese Sprint Race"),
        ("2", "Chinese Grand Prix"),
        ("3", "Japanese Grand Prix"),
        ("4", "Bahrain Grand Prix"),
        ("5", "Saudi Arabian Grand Prix"),
        ("6S", "Miami Sprint Race"),
        ("6", "Miami Grand Prix"),
        ("7", "Emilia-Romagna Grand Prix"),
        ("8", "Monaco Grand Prix"),
        ("9", "Spanish Grand Prix"),
        ("10", "Canadian Grand Prix"),
        ("11", "Austrian Grand Prix"),
        ("12", "British Grand Prix"),
        ("13S", "Belgian Sprint Race"),
        ("13", "Belgian Grand Prix")
    ]
}
